# Generated by Django 4.2.2 on 2024-05-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_answer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_model',
            name='unique_value1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
